Repository jumaallan/android-mpesa-api, pull requests merged in 2021-08, with the labels that each got.

#63 Updating the README.md
  README.md
  screenshots/daraja-success-interface.jpg
  screenshots/daraja-user-interface.jpg
Labels: enhancement, good first issue

#68 Publish to MavenCentral()
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  daraja/build.gradle.kts
  daraja/gradle.properties
Labels: enhancement, fix

#69 Feature fix build plugins
  app/build.gradle.kts
  app/src/main/java/com/androidstudy/mpesa/ui/PaymentActivity.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  daraja/build.gradle.kts
  daraja/src/main/java/com/androidstudy/daraja/Daraja.kt
  daraja/src/main/java/com/androidstudy/daraja/callback/DarajaCallback.kt
  daraja/src/main/java/com/androidstudy/daraja/callback/DarajaPaymentCallback.kt
  daraja/src/main/java/com/androidstudy/daraja/callback/DarajaResult.kt
  daraja/src/main/java/com/androidstudy/daraja/data/repo/DarajaRepository.kt
  daraja/src/main/java/com/androidstudy/daraja/network/ApiClient.kt
  daraja/src/main/java/com/androidstudy/daraja/network/okhttp/UnsafeOkHttpClient.kt
  detekt.yml
Labels: bug

#72 Dokka Docs
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/androidstudy/mpesa/ui/PaymentActivity.kt
  app/src/main/res/layout/activity_payment.xml
  app/src/main/res/layout/content_payment.xml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  daraja/build.gradle.kts
  daraja/src/main/java/com/androidstudy/daraja/Builder.kt
  daraja/src/main/java/com/androidstudy/daraja/Daraja.kt
  daraja/src/main/java/com/androidstudy/daraja/callback/DarajaCallback.kt
  daraja/src/main/java/com/androidstudy/daraja/callback/DarajaException.kt
  daraja/src/main/java/com/androidstudy/daraja/callback/DarajaPaymentCallback.kt
  daraja/src/main/java/com/androidstudy/daraja/callback/DarajaResult.kt
  daraja/src/main/java/com/androidstudy/daraja/data/model/AccessToken.kt
  daraja/src/main/java/com/androidstudy/daraja/data/model/ErrorResponse.kt
  daraja/src/main/java/com/androidstudy/daraja/data/model/LNMExpress.kt
  daraja/src/main/java/com/androidstudy/daraja/data/model/PaymentResult.kt
  daraja/src/main/java/com/androidstudy/daraja/data/repo/DarajaRepository.kt
  daraja/src/main/java/com/androidstudy/daraja/network/ApiClient.kt
  daraja/src/main/java/com/androidstudy/daraja/network/AuthAPI.kt
  daraja/src/main/java/com/androidstudy/daraja/network/LNMAPI.kt
  daraja/src/main/java/com/androidstudy/daraja/network/okhttp/AccessTokenInterceptor.kt
  daraja/src/main/java/com/androidstudy/daraja/network/okhttp/AuthInterceptor.kt
  daraja/src/main/java/com/androidstudy/daraja/network/okhttp/UnsafeOkHttpClient.kt
  daraja/src/main/java/com/androidstudy/daraja/util/Environment.kt
  daraja/src/main/java/com/androidstudy/daraja/util/Settings.kt
  daraja/src/main/java/com/androidstudy/daraja/util/TransactionType.kt
  settings.gradle.kts
Labels: enhancement
